src/Entity/Barman.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BarmanRepository")
 */
class Barman
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $drank_naam;

    /**
     * @ORM\Column(type="integer")
     */
    private $prijs;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $beschrijving;

    /**
     * @ORM\Column(type="boolean")
     */
    private $alcohol;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bestelling", mappedBy="barman")
     */
    private $bestellings;

    public function __construct()
    {
        $this->bestellings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDrankNaam(): ?string
    {
        return $this->drank_naam;
    }

    public function setDrankNaam(string $drank_naam): self
    {
        $this->drank_naam = $drank_naam;

        return $this;
    }

    public function getPrijs(): ?int
    {
        return $this->prijs;
    }

    public function setPrijs(int $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    public function getBeschrijving(): ?string
    {
        return $this->beschrijving;
    }

    public function setBeschrijving(?string $beschrijving): self
    {
        $this->beschrijving = $beschrijving;

        return $this;
    }

    public function getAlcohol(): ?bool
    {
        return $this->alcohol;
    }

    public function setAlcohol(bool $alcohol): self
    {
        $this->alcohol = $alcohol;

        return $this;
    }

    /**
     * @return Collection|Bestelling[]
     */
    public function getBestellings(): Collection
    {
        return $this->bestellings;
    }

    public function addBestelling(Bestelling $bestelling): self
    {
        if (!$this->bestellings->contains($bestelling)) {
            $this->bestellings[] = $bestelling;
            $bestelling->setBarman($this);
        }

        return $this;
    }

    public function removeBestelling(Bestelling $bestelling): self
    {
        if ($this->bestellings->contains($bestelling)) {
            $this->bestellings->removeElement($bestelling);
            // set the owning side to null (unless already changed)
            if ($bestelling->getBarman() === $this) {
                $bestelling->setBarman(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getDrankNaam();
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Barman;
use App\Entity\Bestelling;
use App\Entity\MenuItem;
use App\Entity\Tafel;
use App\Entity\Reservatie;
use App\Form\BestellingType;
use App\Form\BestelType;
use App\Form\ReserveringType;

use \DateTime;

// Include Dompdf required namespaces
use Dompdf\Dompdf;
use Dompdf\Options;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints\Date;

class DefaultController extends AbstractController
{
    /**
 * @Route("/", name="default")
 */
    public function index()
    {
        $repo = $this->getDoctrine();

        $tafels = $repo->getRepository(Tafel::class)->findAll();

        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'tafels' => $tafels,
        ]);
    }

    /**
     * @Route("/menukaart", name="menukaart")
     */
    public function menukaart()
    {
        $repo = $this->getDoctrine();

        $menus = $repo->getRepository(MenuItem::class)->findAll();
        $dranken = $repo->getRepository(Barman::class)->findAll();

        return $this->render('default/menukaart.html.twig', [
            'controller_name' => 'DefaultController',
            'menus' => $menus,
            'dranken' => $dranken,
        ]);
    }

    /**
     * @Route("/reserveer", name="reserveer", methods={"GET","POST"})
     */
    public function reserveer(Request $request): Response
    {
        $reservatie = new Reservatie();

        $repo = $this->getDoctrine();
        $tafels = $repo->getRepository(Tafel::class)->findAll();

        $form = $this->createForm(ReserveringType::class, $reservatie);
        $form->handleRequest($request);
        $formData = $form->getData();

        $datetime = new DateTime();

        if ($form->isSubmitted() && $form->isValid()) {

            if ($reservatie->getTafel()->getGereserveerd() == 1) {
                echo "De gekozen tafel is gereserveerd";
            } else if ($reservatie->getTafel()->getGereserveerd() == 0) {
                $reservatie->setDatum($datetime);
                $reservatie->setTijd($datetime);

                $reservatie->getTafel()->setGereserveerd(1);

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($reservatie);
                $entityManager->flush();

                return $this->redirectToRoute('reserveringen');
            }
        }

        return $this->render('default/reserveer.html.twig', [
            'reservatie' => $reservatie,
            'tafels' => $tafels,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/reserveringen", name="reserveringen")
     */
    public function reserveringen()
    {
        $repo = $this->getDoctrine();

        $reservaties = $repo->getRepository(Reservatie::class)->findAll();

        return $this->render('default/reserveer_overzicht.html.twig', [
            'controller_name' => 'DefaultController',
            'reservaties' => $reservaties,
        ]);
    }

    /**
     * @Route("/reserveringen/{id}", name="bestellen", methods={"GET","POST"})
     */
    public function new(Request $request,Reservatie $reservatie ,$id): Response
    {
        $bestelling = new Bestelling();
        $datetime = new DateTime();

        $form = $this->createForm(BestelType::class, $bestelling);
        $form->handleRequest($request);

        $formData = $form->getData();

        if ($form->isSubmitted() && $form->isValid()) {

            $bestelling->setMenuItem($formData->getmenuItem());
            $bestelling->setBarman($formData->getbarman());
            $bestelling->setReservatie($reservatie);
            $bestelling->setDatum($datetime);
            $bestelling->setTijd($datetime);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bestelling);
            $entityManager->flush();

            $bestellingen = $reservatie->getBestellings();

            $totalMenu = 0;
            $totalDrank = 0;

            foreach($bestellingen as $menus) {
                if ($menus->getMenuItem() == null) {
                    $totalMenu = 0;
                } else {
                    $totalMenu += $menus->getMenuItem()->getPrijs();
                }
            }

            foreach($bestellingen as $dranken) {
                if ($dranken->getBarman() == null) {
                    $totalDrank = 0;
                } else {
                    $totalDrank += $dranken->getBarman()->getPrijs();
                }

            }

            $total = $totalMenu + $totalDrank;

            // Configure Dompdf according to your needs
            $pdfOptions = new Options();
            $pdfOptions->set('defaultFont', 'Arial');
            // Instantiate Dompdf with our options
            $dompdf = new Dompdf($pdfOptions);
            // Retrieve the HTML generated in our twig file
            $html = $this->renderView('default/bon.html.twig', [
                'bestelling' => $bestelling,
                'bestellingen' => $bestellingen,
                'total' => $total,
            ]);
            // Load HTML to Dompdf
            $dompdf->loadHtml($html);
            // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
            $dompdf->setPaper('A4', 'portrait');
            // Render the HTML as PDF
            $dompdf->render();
            // Output the generated PDF to Browser (inline view)
            $dompdf->stream("mypdf.pdf", [
                "Attachment" => false
            ]);

            return $this->render('default/bestellen.html.twig', [
                'controller_name' => 'DefaultController',
                'bestelling' => $bestelling,
                'bestellingen' => $bestellingen,
            ]);
        }

        return $this->render('default/bestellen.html.twig', [
            'bestelling' => $bestelling,
            'reservatie' => $reservatie,
            'form' => $form->createView(),
        ]);
    }



}

templates/default/bestel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h4>Reservering: {{ reservering.naam }}</h4>

    <p>Selecteer producten die je wilt bestellen</p>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Bestel') }}</button>
    {{ form_end(form) }}

{% endblock %}

templates/default/bestellen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Bestellen </h1>

    <h2>{{ reservatie.naam }}</h2>
    <br>
    <div>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}

    </div>

{% endblock %}

templates/default/bon.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Bon </h1>

    <p>Reservering: {{ bestelling.reservatie.naam }}</p>
    {% if bestelling.reservatie.klant is null %}
            <p>Gereserveerde: Anoniem</p>
        {% else %}
            <p>Gereserveerde: {{ bestelling.reservatie.klant.naam }}</p>
    {% endif %}
    <p>Gereserveerde Tafel: {{ bestelling.reservatie.tafel }}</p>
    <hr>
    <div>

        {% for bestelling in bestellingen %}
            {% if bestelling.menuItem is null %}
            {% else %}
                <p>Product: {{ bestelling.menuItem.naam }} .... Prijs: {{ bestelling.menuItem.prijs }}</p>
            {% endif %}
        {% endfor %}

        {% for bestelling in bestellingen %}
            {% if bestelling.barman is null %}
                {% else %}
                    <p>Product: {{ bestelling.barman.DrankNaam }} .... Prijs: {{ bestelling.barman.prijs }}</p>
            {% endif %}
        {% endfor %}

    </div>
    <p>Totaal: {{ total }}</p>
    <hr>

    <p>Datum: {{ bestelling.datum|date('d-m-Y') }} | Tijd: {{ bestelling.tijd|date('h:i') }}</p>
    <br>
    <p>Excellent Taste</p>

{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Excellent Taste </h1>

    <div>
        <a href="{{ path('reserveer') }}"><h4>Reserveer Nu</h4></a>
        <hr>
        <a href="{{ path('menukaart') }}"><h4>Bekijk het menukaart</h4></a>
        <hr>
        <h4>Tafels Overzicht</h4>
        <div>
            <p>Alle Tafels:</p>
            <div>
                <div>
                    {% for tafel in tafels %}
                        {{ tafel.nummer }}
                    {% endfor %}
                </div>
            </div>
            <br>
            <p>Beschikbare Tafels:</p>
            <div>
                <div>
                    {% for tafel in tafels %}
                        {% if tafel is defined and tafel.gereserveerd == 0 %}
                            {% if tafel.nummer is empty %}
                                    <p>Helaas zijn we vol geboekt, Probeer eens later.</p>
                                {% endif %}
                            {{ tafel.nummer }}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br>
            <p>Gereserveerde Tafels:</p>
            <div>
                <div>
                    {% for tafel in tafels %}
                        {% if tafel is defined and tafel.gereserveerd == 1 %}
                            {{ tafel.nummer }}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <hr>

        {#<h4>Admin Paginas</h4>#}
        {#<div>#}
            {#<div>#}
                {#<p>Test</p>#}
            {#</div>#}
            {#<div>#}
                {#<p>Yeet</p>#}
            {#</div>#}
        {#</div>#}

    </div>
{% endblock %}

templates/default/menu.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h4>Menukaart</h4>

    <p>Alle Menu's</p>

    <div style="display: flex;">

        {% for menuItem in menuItems %}
            <div class="card" style="width: 18rem; margin: 1%;">
                <img style="max-width: 100%;" class="card-img-top" src="{{ asset(menuItem.image) }}">
                <div class="card-body">
                        <p class="card-title">{{ menuItem.naam }}</p>
                        <p class="card-text">€&nbsp;{{ menuItem.prijs }},00</p>
                    <p class="card-text">Gerechten:</p>
                    <ul style="list-style-type: none">
                        <li>test</li>
                    </ul>
                </div>
            </div>
        {% endfor %}

    </div>

    <p>Dranken zonder alcohol:</p>

    {% for barman in barmannen %}
        {% if barman is defined and barman.alcohol == 0 %}
            <div class="card" style="width: 18rem; margin: 1%;">
                {#<img style="max-width: 100%;" class="card-img-top" src="{{ asset(menuItem.image) }}">#}
                <div class="card-body">
                    <p class="card-title">{{ barman.drank }}</p>
                    <p class="card-text">€&nbsp;{{ barman.prijs }},00</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    <p>Dranken met alcohol:</p>
    {% for barman in barmannen %}
        {% if barman is defined and barman.alcohol == 1 %}
            <div class="card" style="width: 18rem; margin: 1%;">
                {#<img style="max-width: 100%;" class="card-img-top" src="{{ asset(menuItem.image) }}">#}
                <div class="card-body">
                    <p class="card-title">{{ barman.drank }}</p>
                    <p class="card-text">€&nbsp;{{ barman.prijs }},00</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endblock %}

templates/default/menukaart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Menukaart </h1>

    <p>Alle menus</p>
    <div>
        {% for menu in menus %}
            <p>{{ menu.image }}</p>
            <p>{{ menu.naam }}</p>
            {% if menu.beschrijving is empty %}
                    <p>Geen Beschrijving</p>
                {% else %}
                    <p>{{ menu.beschrijving }}</p>
            {% endif %}
            <p>{{ menu.prijs }}</p>
        {% endfor %}
    </div>
<hr>
    <p>Alle Dranken</p>
    <div>
        {% for drank in dranken %}
            <p>{{ drank.drankNaam }}</p>
            <p>{{ drank.beschrijving }}</p>
            <p>{{ drank.prijs }}</p>
            <p>{{ drank.alcohol }}</p>
        {% endfor %}
    </div>

{% endblock %}

templates/default/reserveer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Reserveer </h1>

    <div>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}

    </div>

    <hr>
    <h4>Tafels Overzicht</h4>
    <div>
        <p>Alle Tafels:</p>
        <div>
            <div>
                {% for tafel in tafels %}
                    {{ tafel.nummer }}
                {% endfor %}
            </div>
        </div>
        <br>
        <p>Beschikbare Tafels:</p>
        <div>
            <div>
                {% for tafel in tafels %}
                    {% if tafel is defined and tafel.gereserveerd == 0 %}
                            {{ tafel.nummer }}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>
        <p>Gereserveerde Tafels:</p>
        <div>
            <div>
                {% for tafel in tafels %}
                    {% if tafel is defined and tafel.gereserveerd == 1 %}
                        {{ tafel.nummer }}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}

templates/default/reserveer_overzicht.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1> Reserveringen </h1>
    <p>klik op een reservering om te bestellen</p>
    <div>

        {% for reservatie in reservaties %}

            <div>
                <a href="{{ path('bestellen', {'id': reservatie.id} ) }}">{{ reservatie.naam }}</a>
            </div>

        {% endfor %}

    </div>

{% endblock %}

templates/default/reservering_bestellen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <p>Reserveringen</p>

    <span>Klik op een reservering om te bestellen</span>

    <br><br>

    <div>
        {% for reservering in reserverings %}

            <a href="{{ path('bestel', {'id': reservering.id}) }}">{{ reservering.naam }}</a>
            <br>

        {% endfor %}

    </div>


{% endblock %}